#!/bin/bash

# Get the location of this script - should be in the Blender folder
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd ${DIR}
# Run the API update script
./blender.app/Contents/MacOS/blender -b -P python_api/pypredef_gen.py
